services:
  python:
    build:
      context: .
    ports:
      - "8001:8000"
    env_file:
      - .env.prod
    environment:
      - PYTHONPATH=/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000