services:
  nginx:
    build:
      context: ../autodeclic-react
      dockerfile: Dockerfile.prod
    container_name: reverse-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - /opt/certbot/www:/var/www/certbot:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      symfony:
        condition: service_healthy
      python:
        condition: service_started
    networks:
      - ${DOCKER_NETWORK}
    healthcheck:
      test: ["CMD", "nginx", "-t"]
      interval: 10s
      timeout: 5s
      retries: 3

  symfony:
    build:
      context: ../autodeclic-symfony
      dockerfile: Dockerfile.prod
    container_name: symfony
    networks:
      - ${DOCKER_NETWORK}
    depends_on:
      database:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "php", "bin/console", "doctrine:query:sql", "SELECT 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    volumes:
      - ../autodeclic-symfony:/app
      - ~/.config/gcloud:/root/.config/gcloud

  database:
    image: mysql:${MYSQL_VERSION}
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "127.0.0.1:3306:3306"
    networks:
      - ${DOCKER_NETWORK}
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${MYSQL_ROOT_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  python:
    build:
      context: ../autodeclic-python
    container_name: python
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    volumes:
      - ../autodeclic-python:/app
    networks:
      - ${DOCKER_NETWORK}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s

volumes:
  chrome_data:
  mysql_data:
  
networks:
  autodeclic-network:
    external: true